name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'chore(release):')
    uses: ./.github/workflows/validate.yml

  release:
    needs: ci
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.release_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npm run build

      - name: Configure git author
        uses: MaxiGarcia13/gh-actions/.github/actions/configure-git-author@main

      - name: Release library
        run: npm run release:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump app version
        run: npm run version:app

      - name: Push commit and tags
        run: git push && git push --tags

  release-notes:
    if: ${{ needs.release.outputs.tag != '' }}
    permissions:
      contents: write
    needs: release
    uses: MaxiGarcia13/gh-actions/.github/workflows/create-release-notes.yml@main
    with:
      tag: ${{ needs.bump.outputs.tag }}
      default_branch: main
